name: Checks

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  PY_COLORS: "1"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - black
        - flake8
        - isort
        - minify
        - pylint
        - readme
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools tox wheel
    - name: Run ${{ matrix.env }}
      run: tox -e ${{ matrix.env }}
